// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildImage(arg1) {
  return window['go']['main']['App']['BuildImage'](arg1);
}

export function CheckMyBoxFile(arg1) {
  return window['go']['main']['App']['CheckMyBoxFile'](arg1);
}

export function DeleteContainer(arg1) {
  return window['go']['main']['App']['DeleteContainer'](arg1);
}

export function GetHostIP() {
  return window['go']['main']['App']['GetHostIP']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function ListContainers() {
  return window['go']['main']['App']['ListContainers']();
}

export function ListImages() {
  return window['go']['main']['App']['ListImages']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RemoveImage(arg1) {
  return window['go']['main']['App']['RemoveImage'](arg1);
}

export function RunContainer(arg1) {
  return window['go']['main']['App']['RunContainer'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UpdateContainerResources(arg1, arg2) {
  return window['go']['main']['App']['UpdateContainerResources'](arg1, arg2);
}
