// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildImage(arg1:main.BuildImageReq):Promise<any>;

export function DeleteContainer(arg1:string):Promise<any>;

export function GetSystemStats():Promise<any>;

export function ListContainers():Promise<any>;

export function ListImages():Promise<any>;

export function RemoveImage(arg1:string):Promise<any>;

export function RunContainer(arg1:main.RunContainerReq):Promise<any>;

export function SelectDirectory():Promise<string>;

export function UpdateContainerResources(arg1:string,arg2:main.UpdateResourceReq):Promise<any>;
